# Site settings
title: "ProntoPiso"
version: "v1"
description: "Precio garantizado en 90 días"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: css

# Exclude this stuff
exclude: [node_modules, gulpfile.js, docker, Dockerfile, Makefile, .dockerignore]

# Gems
gems:
  - jekyll-seo-tag
